project:
  type: book
  pre-render: pre_render.R
brand: ucl_brand.yml
book:
  title: The problem with the OME metric
  search: false
  downloads: [pdf,docx]
  chapters:
    - index.qmd
    - manuscript.qmd
    - references.qmd
  appendices:
    - appendix.qmd
    - simulation.qmd
comments:
  hypothesis:
    theme: clean
bibliography: /Users/dylanwhitaker/Library/CloudStorage/OneDrive-UniversityCollegeLondon/refs.bib
csl: elsevier-vancouver.csl
format:
  html:
    toc: true
    fig-align: center
    fig-width: 6.5
    fig-height: 4
    fig-dpi: 150
  pdf:
    documentclass: scrreprt
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    toc: true
    fig-align: center
    fig-width: 5
    fig-height: 3
    fig-dpi: 300
  docx:
    toc: true
    fig-align: center
    fig-width: 5
    fig-height: 3
    fig-dpi: 300
prefer-html: true
crossref:
  lof-title: List of Figures
execute:
  echo: false
  warning: true
  error: true
author:
  - id: aut1
    name:
      given: Dylan
      family: Whitaker
    email: dylan.whitaker.25@ucl.ac.uk
    orcid: 0000-0002-6619-5846
    attributes:
      corresponding: true
    roles:
      - Conceptualization
      - Data curation
      - Formal analysis
      - Methodology
      - Visualization
      - Writing - original draft
      - Writing - review & editing
    affiliations:
      - ref: aff1
      - ref: aff2
  - id: aut2
    name:
      given: Matthew
      family: Wilson
    orcid: 0000-0002-5001-0253
    attributes:
      corresponding: false
    roles:
      - Conceptualization
      - Funding acquisition
      - Supervision
      - Writing - review & editing
    affiliations:
      - ref: aff3
      - ref: aff4
  - id: aut3
    name:
      given: Steve
      family: Harris
    orcid: 0000-0002-5001-0253
    attributes:
      corresponding: false
    roles:
      - Conceptualization
      - Funding acquisition
      - Supervision
      - Writing - review & editing
    affiliations:
      - ref: aff1
      - ref: aff2
affiliations:
  - id: aff1
    name: Institute of Health Informatics, University College London, London, United
      Kingdom
  - id: aff2
    name: Department of Critical Care, University College London Hospitals NHS Foundation
      Trust, London, United Kingdom
  - id: aff3
    name: Department of Anaesthesia and Perioperative Medicine, University College
      London Hospitals NHS Foundation Trust, London, United Kingdom
  - id: aff4
    name: Division of Surgery and Interventional Science, University College London,
      London, United Kingdom
