# Author contributions
```{r}
#| echo: false
#| message: false
#| warning: false
#| output: asis
#| eval: false

tbl_authors <- googlesheets4::read_sheet("123JiCxSHvA7Wiaz6tU25B7Wq27Ty_cV7n6UUqlhyvrY",sheet = 2)
aut <- plume::Plume$new(tbl_authors, dotted_initials = F)
aut$get_contributions(roles_first = T)
```

Conceptualization: DW, MW and SH\
Data curation: DW\
Formal analysis: DW\
Funding acquisition: MW and SH\
Methodology: DW\
Supervision: MW and SH\
Visualization: DW\
Writing - original draft: DW\
Writing - review & editing: DW, MW and SH\

# Acknowledgements

The authors wish to thank the following for their support: Dr Thomas Frost for early direction and support, Dr Yogini Jani for feedback, University College London Hospitals National Health Service Foundation Trust Critical Care Special Interest Project Scheme and the University College London Health Algorithm Laboratory.

# Declaration of interests

The authors declare that they have no conflict of interest

# Funding 

DW is supported by the Engineering and Physical Sciences Research Council (EP/Y034929/1). MW and SH are supported by the National Institute for Health Research (NIHR) Central London Patient Safety Research Collaboration (NIHR 204297). SH and DW are supported by the NIHR University College London Hospitals National Health Service Foundation Trust and University College London Biomedical Research Centre. The views expressed in this study are those of the authors and do not necessarily reflect those of the NIHR or the Department of Health and Social Care.
